### PR TITLE
Make the authorize page redirect to login if user logged out

### PR DESCRIPTION
**Pull request by zacps**
If the user logs out in the middle of the authorisation grant they will be redirected back to the login page and be able to successfully complete the authorisation flow.

### CODE REVIEW

**Comment by adamlynam-catalyst** [comment]
LGTM

**Review by adamlynam-catalyst — APPROVED** [review]

**Comment by zacps** [comment]
I do have some slight security concerns about this change, [see here](http://blog.andlabs.org/2010/03/bypassing-csrf-protections-with.html).

This should be fine for [all browsers that support `X-FRAME-OPTIONS`](https://caniuse.com/#feat=x-frame-options) though.

**Comment by adamlynam-catalyst** [comment]
> I do have some slight security concerns about this change, [see here](http://blog.andlabs.org/2010/03/bypassing-csrf-protections-with.html).
> 
> This should be fine for [all browsers that support `X-FRAME-OPTIONS`](https://caniuse.com/#feat=x-frame-options) though.

What is the attack here? An attacker uses a GET parameter to pollute the POST parameter containing the id for the service to authorize?

**Comment by zacps** [comment]
I think you *might* be able to follow the implicit flow, and with changing the `redirect_uri` you might be able to obtain an ID token. I'm not sure I've thought this through though, there may be other things that would stop it from being possible.

**Comment by zacps** [comment]
After some discussion we decided this was not an issue because it would require compromising the client secret and potentially the client's domain, at which point you already have everything you need to impersonate a client.

**Pull request merged**
