### PR TITLE
Add support for using protected_resource_view on methods

### PR DESCRIPTION
**Pull request by zacps**
This lets you use this decorator on class based views and on django-rest-framework views.

### CODE REVIEW

**Comment by zacps** [comment]
I've decided to [raise an issue on django-rest-framework](https://github.com/encode/django-rest-framework/issues/7176) about allowing permissions classes more control over the response. This may let us implement proper authentication and permissions classes for rest framework views, but I don't think it's worth waiting for.

**Review by adamlynam-catalyst — APPROVED** [review]
Is inside `oauth2.py` the right place for `_MethodDecoratorAdaptor` and `method_or_func` to live?

LGTM though

**Comment by zacps** [comment]
> Is inside `oauth2.py` the right place for `_MethodDecoratorAdaptor` and `method_or_func` to live?

I honestly have no idea.

**Comment by adamlynam-catalyst** [comment]
> > Is inside `oauth2.py` the right place for `_MethodDecoratorAdaptor` and `method_or_func` to live?
> 
> I honestly have no idea.

I should really be more familiar with this codebase. :man_facepalming:

Perhaps moving it to somewhere more generic is just overthinking it.

**Comment by zacps** [comment]
Potentially lib/utils/common? I feel like that file is kind of overloaded at the moment because it contains some internal functions and some hook defaults.

**Comment by zacps** [comment]
Related: #19

**Comment by adamlynam-catalyst** [comment]
> Potentially lib/utils/common? I feel like that file is kind of overloaded at the moment because it contains some internal functions and some hook defaults.

I think `lib/utils/common` is better, but even better again might be a new `lib/utils/functools`? My thinking is that `_MethodDecoratorAdaptor` and ultimately `method_or_func` are extentions of other higher order functions like `wraps` that come from the core `functools`.

Having said that though. There is so little code in the provider that this level of code separation feels like it might be overkill and leaving things as they are might be the right answer; at least until we need to use `method_or_func` elsewhere.

**Comment by zacps** [comment]
I think it's fine to leave it like this for now. It can be moved later if necessary.

**Pull request merged**
